# Generated by Django 3.2.23 on 2024-01-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20240131_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='product_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
