# Generated by Django 3.2.23 on 2024-01-31 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_discount'),
        ('ratings', '0003_alter_userrating_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrating',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='products.product'),
        ),
    ]
