# Generated by Django 3.2.23 on 2024-01-31 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_alter_userrating_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='product_name',
        ),
    ]
