# Generated by Django 3.2.23 on 2024-02-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_remove_userrating_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrating',
            old_name='product_id',
            new_name='product',
        ),
    ]
