# Generated by Django 3.2.23 on 2024-01-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_orderlineitem_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='original_cart',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stripe_pid',
            field=models.CharField(default='', max_length=254),
        ),
    ]
