# Generated by Django 3.2.23 on 2024-01-28 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0004_alter_purchase_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='profiles.userprofile'),
        ),
    ]
